
[master]
name            = "Mod Panels++"
tags            = ["Tool", "Must be run on Server"]
autodescription = true
description     = "README.md"
preview         = "preview.jpg"

[beta]
name            = "Mod Panels++ - beta"
tags            = ["Tool", "Must be run on Server"]
autodescription = false
description     = "description.beta.txt"
preview         = "preview.jpg"
